export const projectsData = [
  // { example
  //   id: 0,
  //   title: "Paint Your Pixture",
  //   media:  [
  //     "https://www.youtube.com/embed/v_7VDm1LEqY?enablejsapi=1&rel=0",
  //     "/images/projects/paint-your-picture/paint-your-picture-01-clip.mp4",
  //     "/images/projects/paint-your-picture/paint-your-picture-cover.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-01.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-02.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-03.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-04.jpg",
  // ],
  //   links: [],
  //   description:
  //     "This was a site challenge to match the css style requirements from an image.",
  //   tags: [
  //     "React",
  //     "CSS",
  //     "Sass",
  //     "Unreal Engine",
  //     "Photoshop",
  //     "Nodejs",
  //     "UX",
  //     "Vite",
  //   ],
  //   achievements: [
  //     "Made functional site from static image within a given time frame.",
  //     "Leaned new css tricks. The corner fold.",
  //     "Side bar fades on page scroll position.",
  //     "Used gsap to make cool staggered animations and transitions.",
  //   ],
  // },
  {
    id: 16,
    title: "AI Image Reviewer",
    media: ["/images/misc/project-placeholder.jpg"],
    links: [
      { type: "github", url: "https://github.com" },
      { type: "site", url: "https://example.com" },
    ],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs", "Top 5"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 18,
    title: "Asset Approvals",
    media: ["/images/misc/project-placeholder.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs", "Top 5"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 17,
    title: "Asset Management System",
    media: ["/images/misc/project-placeholder.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 1,
    title: "Star Wars Secrets of the Empire",
    media: ["/images/projects/star-wars/star-wars-01.jpg"],
    links: [],
    description: "A virtual reality experience made for Disney!",
    tags: [
      "Unity",
      "Maya",
      "Substance",
      "Adobe CS",
      "ZBrush",
      "Python",
      "C#",
      "Video Games",
      "Virtual Reality",
    ],
    achievements: [
      "Built edge normalizer tool to achieve smooth bevels with minimal geometry.",
      "Created Story board and animatic for whole experience.",
      "Featured at DisneyLand and Disney World resorts is quite a badge of honor.",
      "Getting to work with Disney and Star Wars!",
    ],
  },
  {
    id: 2,
    title: "Ghostbusters",
    media: [
      "/images/projects/ghostbusters/ghostbusters-01.jpg",
      "/images/projects/ghostbusters/ghostbusters-02.jpg",
    ],
    links: [],
    description: "A Virtual Reality experience made at the Void.",
    tags: [
      "Unity",
      "Maya",
      "Substance",
      "Adobe CS",
      "ZBrush",
      "Python",
      "C#",
      "Video Games",
      "Virtual Reality",
    ],
    achievements: [
      "Small team great results! Proud to be on a small team and achieve something this big.",
      "Learned limitations and how to work within restraints of Virtual Reality.",
      "Built a skin-weight transferring tool, and mass obj exporter increasing productivity by 20%",
      "Art skills used: Story Boarding, Concept Art, 3d Modeling and Animation.",
    ],
  },
  {
    id: 3,
    title: "Athletic Apparel Customizer",
    media: [
      "https://www.youtube.com/embed/v_7VDm1LEqY?enablejsapi=1&rel=0",
      "/images/projects/fsg-builder/fsg-builder-01.jpg",
      "/images/projects/fsg-builder/fsg-builder-02.jpg",
      "/images/projects/fsg-builder/fsg-builder-03.jpg",
      "/images/projects/fsg-builder/fsg-builder-04.jpg",
      "/images/projects/fsg-builder/fsg-builder-05.jpg",
    ],
    links: [],
    description: "An athletic apparel customization tool.",
    tags: ["React", "CSS", "Redux", "Adobe CS", "PostgreSQL", "Nodejs"],
    achievements: [
      "I was in charge of visual representation of the data on canvas and canvas interactions.",
      "Did tons of math and geometry to match scale, detect edges and resize elements.",
      "Organize a giant yet powerful redux state to manage iteraction accross app and canvas.",
    ],
  },
  {
    id: 4,
    title: "Athletic Apparel Store",
    media: [
      "/images/projects/fsg-store/fsg-store-01.jpg",
      "/images/projects/fsg-store/fsg-store-02.jpg",
      "/images/projects/fsg-store/fsg-store-03.jpg",
      "/images/projects/fsg-store/fsg-store-04.jpg",
      "/images/projects/fsg-store/fsg-store-05.jpg",
      "/images/projects/fsg-store/fsg-store-06.jpg",
      "/images/projects/fsg-store/fsg-store-07.jpg",
      "/images/projects/fsg-store/fsg-store-08.jpg",
    ],
    links: [],
    description:
      "A ecomerce store used to catalogued, displayed and purchase athletic apparel.",
    tags: ["React", "CSS", "Redux", "Adobe CS", "PostgreSQL", "Nodejs"],
    achievements: [
      "Made universal image component used on all pages. Leveraging reacts component based architecture.",
      "Created the multi-tier filtering system to sort through over 2000 products.",
      "Set up a component based svg system to allow javascript to control svg's dynamically.",
      "Even though I was a Software Engineer, I also got tasked with the UX Design and Mockups.",
    ],
  },
  {
    id: 5,
    title: "Minions Paradise",
    media: [
      "/images/projects/minions-paradise/minions-paradise-cover.jpg",
      "/images/projects/minions-paradise/unique-cruiseship.jpg",
      "/images/projects/minions-paradise/minion-base.jpg",
      "/images/projects/minions-paradise/minion-beedo.jpg",
      "/images/projects/minions-paradise/minion-french-maid.jpg",
      "/images/projects/minions-paradise/resource-banana.jpg",
      "/images/projects/minions-paradise/resource-fireflies.jpg",
      "/images/projects/minions-paradise/resource-piranha.jpg",
      "/images/projects/minions-paradise/resource-razorclam.jpg",
      "/images/projects/minions-paradise/resource-rubbertree.jpg",
      "/images/projects/minions-paradise/decor-camelrocks.jpg",
      "/images/projects/minions-paradise/decor-clothesline.jpg",
      "/images/projects/minions-paradise/decor-minionsign.jpg",
      "/images/projects/minions-paradise/decor-toilet.jpg",
      "/images/projects/minions-paradise/decor-totemshort.jpg",
      "/images/projects/minions-paradise/decor-totemtall.jpg",
      "/images/projects/minions-paradise/decor-umbrella.jpg",
      "/images/projects/minions-paradise/leisure-hammock.jpg",
      "/images/projects/minions-paradise/leisure-hottub.jpg",
      "/images/projects/minions-paradise/leisure-loungechair.jpg",
      "/images/projects/minions-paradise/leisure-throwingdisc.jpg",
      "/images/projects/minions-paradise/unique-innertube.jpg",
      "/images/projects/minions-paradise/unique-repairstate01.jpg",
      "/images/projects/minions-paradise/unique-repairstate02.jpg",
      "/images/projects/minions-paradise/unique-repairstate03.jpg",
      "/images/projects/minions-paradise/unique-repairstate04.jpg",
      "/images/projects/minions-paradise/unique-repairstate05.jpg",
      "/images/projects/minions-paradise/unique-repairstate06.jpg",
    ],
    links: [],
    description:
      "A mobile resource gathering game made at EA teamed up with Illumination studios.",
    tags: [
      "Unity",
      "Maya",
      "Adobe CS",
      "ZBrush",
      "Python",
      "C#",
      "Video Games",
    ],
    achievements: [
      "Invented a tool that saved company over $150,000 by reducing production time.",
      "I created the project folder structure, naming conventions and modeling pipeline from scratch.",
      "Made customMaya tools in Python tools for Animation, Modeling, LightBaking and exports.",
      "In charge of the design doc organization, keeping a team over 60 all on the same page.",
    ],
  },
  {
    id: 6,
    title: "Monopoly Streets",
    media: ["/images/projects/monopoly-streets/monopoly-streets-cover.jpg"],
    links: [],
    description:
      "Monopoly the video game release on Xbox 360, Playstation 3, and the Wii",
    tags: ["Adobe CS", "Maya", "Video Games", "Python"],
    achievements: [
      "Verified bug fixes and entering data into Dev Track.",
      "I created and ran test cases.",
      "Character concepts.",
    ],
  },
  {
    id: 7,
    title: "Nerf N-Strike",
    media: ["/images/projects/nerf-1/nerf-1-01.jpg"],
    links: [],
    description: "A video game release on the wii.",
    tags: ["Adobe CS", "Maya", "Video Games"],
    achievements: [
      "Assisted with a Sizzle video and some conceptual design.",
      "Creating and running test cases",
      "Verified bug fixes and entering data into Dev Track.",
      "I created and ran test cases.",
    ],
  },
  {
    id: 8,
    title: "Nerf N-Strike Elite",
    media: ["/images/projects/nerf-2/nerf-2-01.jpg"],
    links: [],
    description: "The Sequel to Nerf N-Strike release on Wii.",
    tags: ["Adobe CS", "Maya", "Video Games", "Python"],
    achievements: [
      "Work with Art Director to make Enemy, Environment, Vehicle, and Weapon concepts.",
      "It's not proven but I bet I still have the highest score in the Blasting Chamber.",
      "Verified bug fixes and entering data into Dev Track.",
      "I created and ran test cases.",
    ],
  },
  {
    id: 9,
    title: "Sims 3",
    media: [
      "/images/projects/sims-3/the-sims-3-logo.jpg",
      "/images/projects/sims-3/ep06-bear.jpg",
      "/images/projects/sims-3/ep06-chairpancake.jpg",
      "/images/projects/sims-3/ep06-gargoyal.jpg",
      "/images/projects/sims-3/ep06-photobooth02.jpg",
      "/images/projects/sims-3/ep06-seahorse.jpg",
      "/images/projects/sims-3/ep06-steampunkfurnace.jpg",
      "/images/projects/sims-3/ep07-wands.jpg",
      "/images/projects/sims-3/ep08-baristabar01.jpg",
      "/images/projects/sims-3/ep08-baristabar02.jpg",
      "/images/projects/sims-3/ep08-forgottencabin01.jpg",
      "/images/projects/sims-3/ep08-forgottencabin02.jpg",
      "/images/projects/sims-3/ep08-forgottencabin03.jpg",
      "/images/projects/sims-3/ep08-forgottencabin04.jpg",
      "/images/projects/sims-3/ep08-forgottencabin05.jpg",
      "/images/projects/sims-3/ep08-loveseatcrates.jpg",
      "/images/projects/sims-3/ep08-signbowling.jpg",
      "/images/projects/sims-3/ep08-signcoffeeshop.jpg",
      "/images/projects/sims-3/ep08-vendingmachinecandy.jpg",
      "/images/projects/sims-3/ep09-brainenhance01.jpg",
      "/images/projects/sims-3/ep09-brainenhance02.jpg",
      "/images/projects/sims-3/ep09-photobooth02.jpg",
      "/images/projects/sims-3/ep10-arch01.jpg",
      "/images/projects/sims-3/ep10-arch02.jpg",
      "/images/projects/sims-3/ep10-arch03.jpg",
    ],
    links: [],
    description:
      "This is a life simulation game with character customization and house building.",
    tags: ["Maya", "ZBrush", "Adobe CS", "Python", "C#", "Video Games"],
    achievements: [
      "I take pride in working on a game that has more then ten million copies sold.",
      "Learned the power of project folder structure and naming conventions.",
      "Created modular system to work with grid based custom home builder.",
      "Presented to over 100 coworkers monthly, on teams achievements and progress.",
    ],
  },
  {
    id: 10,
    title: "Sims 4",
    media: ["/images/projects/sims-4/sims-4-cover.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["Maya", "ZBrush", "Adobe CS", "Python", "C#", "Video Games"],
    achievements: [
      "Made custom maya toolbar to aid with modeling, rigging and exporting.",
      "Got flown out to EA Headquarters to work on project for 2 months.",
      "Updated base game assets to be more versatile for use in future expansion packs.",
      "Part of process for desinging and implementing new texture and style system",
    ],
  },
  {
    id: 11,
    title: "Sims Freeplay",
    media: [
      "/images/projects/sims-freeplay/sims-freeplay-cover.jpg",
      "/images/projects/sims-freeplay/sims-freeplay-barnAssets-01.jpg",
      "/images/projects/sims-freeplay/sims-freeplay-barnAssets-02.jpg",
      "/images/projects/sims-freeplay/sims-freeplay-barnAssets-03.jpg",
    ],
    links: [],
    description: "Sims Mobiles predecessor.",
    tags: ["Maya", "ZBrush", "Adobe CS", "Python", "C#", "Video Games"],
    achievements: [
      "Flew out to Melbourne Australia for 2 Months to assist and learn how to develop games for mobile.",
      "Challenged to meet a visual quality with the restrictions of being on mobile devices.",
    ],
  },
  {
    id: 12,
    title: "Sims Mobile",
    media: ["/images/projects/sims-mobile/sims-mobile-cover.jpg"],
    links: [],
    description: "Sims game made for Mobile!",
    tags: ["Maya", "ZBrush", "Adobe CS", "Python", "C#", "Video Games"],
    achievements: [
      "Challenged to meet a visual quality with the restrictions of being on mobile devices.",
      "Developed deeper understanding of the Unity 3d engine.",
    ],
  },
  {
    id: 13,
    title: "Tropicana Tropolis",
    media: [
      "/images/projects/tropicana-tropolis/tropolis-cover.jpg",
      "/images/projects/tropicana-tropolis/tropolis-mockup.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b1.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b2.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b3.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b4.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b5.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b6.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b7.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b8.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b9.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketch1.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketch2.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches1.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches2.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches3.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches4.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches5.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches6.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches7.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches8.jpg",
    ],
    links: [],
    description:
      "A flash site made for a new product that Tropicana was releasing, with games, puzzles and activities for kids.",
    tags: ["Flash", "Adobe CS"],
    achievements: [
      "FWA Award winning site!",
      "Tradition 2d animated characters and environments.",
      "Made over a dozen coloring book pages for downloadable content.",
      "I was the only artist on the team.",
    ],
  },
  {
    id: 14,
    title: "Akrasia",
    media: [
      "/images/projects/akrasia/akrasia-01.jpg",
      "/images/projects/akrasia/akrasia-02.jpg",
    ],
    links: [],
    description:
      "Users accepts challenges to push themselves outside of their box to achieve goals.",
    tags: [
      "React",
      "CSS",
      "Redux",
      "Nodejs",
      "PostgreSQL",
      "HTML",
      "JavaScript",
    ],
    achievements: [
      "Created a time window using 'Momentjs' for completing, validating and closing challenges.",
      "Made detailed wireframe to keep group in alignment while in development.",
      "Contributed in team discussions to help forsee any issues and create solutions.",
    ],
  },
  {
    id: 15,
    title: "O Captain",
    media: ["/images/projects/o-captain/o-captain-01.jpg"],
    links: [],
    description:
      "An organizational site for teachers allowing them to track student assignments and grades.",
    tags: [
      "React",
      "CSS",
      "Redux",
      "Nodejs",
      "PostgreSQL",
      "HTML",
      "JavaScript",
    ],
    achievements: [
      "Combined multiple tables in PostgreSQL to retrieve large amounts of data through foreign keys.",
      "Created in depth database furthering my understanding of relations databases",
    ],
  },
];
