export const projectsData = [
  // { example
  //   id: 0,
  //   title: "Paint Your Pixture",
  //   media:  [
  //     "https://www.youtube.com/embed/v_7VDm1LEqY?enablejsapi=1&rel=0",
  //     "/images/projects/paint-your-picture/paint-your-picture-01-clip.mp4",
  //     "/images/projects/paint-your-picture/paint-your-picture-cover.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-01.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-02.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-03.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-04.jpg",
  // ],
  //   links: [],
  //   description:
  //     "This was a site challenge to match the css style requirements from an image.",
  //   tags: [
  //     "React",
  //     "CSS",
  //     "Sass",
  //     "Unreal Engine",
  //     "Photoshop",
  //     "Nodejs",
  //     "UX",
  //     "Vite",
  //   ],
  //   achievements: [
  //     "Made functional site from static image within a given time frame.",
  //     "Leaned new css tricks. The corner fold.",
  //     "Side bar fades on page scroll position.",
  //     "Used gsap to make cool staggered animations and transitions.",
  //   ],
  // },
  {
    id: 16,
    title: "AI Image Reviewer",
    media: ["/images/misc/project-placeholder.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 15,
    title: "Asset Approvals",
    media: ["/images/misc/project-placeholder.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 17,
    title: "Asset Management System",
    media: ["/images/misc/project-placeholder.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 1,
    title: "Star Wars Secrets of the Empire",
    media: ["/images/projects/star-wars/star-wars-01.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 2,
    title: "Ghostbusters",
    media: [
      "/images/projects/ghostbusters/ghostbusters-01.jpg",
      "/images/projects/ghostbusters/ghostbusters-02.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 3,
    title: "Athletic Apparel Customizer",
    media: [
      "https://www.youtube.com/embed/v_7VDm1LEqY?enablejsapi=1&rel=0",
      "/images/projects/fsg-builder/fsg-builder-01.jpg",
      "/images/projects/fsg-builder/fsg-builder-02.jpg",
      "/images/projects/fsg-builder/fsg-builder-03.jpg",
      "/images/projects/fsg-builder/fsg-builder-04.jpg",
      "/images/projects/fsg-builder/fsg-builder-05.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 4,
    title: "Athletic Apparel Store",
    media: [
      "/images/projects/fsg-store/fsg-store-01.jpg",
      "/images/projects/fsg-store/fsg-store-02.jpg",
      "/images/projects/fsg-store/fsg-store-03.jpg",
      "/images/projects/fsg-store/fsg-store-04.jpg",
      "/images/projects/fsg-store/fsg-store-05.jpg",
      "/images/projects/fsg-store/fsg-store-06.jpg",
      "/images/projects/fsg-store/fsg-store-07.jpg",
      "/images/projects/fsg-store/fsg-store-08.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 5,
    title: "Minions Paradise",
    media: [
      "/images/projects/minions-paradise/minions-paradise-cover.jpg",
      "/images/projects/minions-paradise/unique-cruiseship.jpg",
      "/images/projects/minions-paradise/minion-base.jpg",
      "/images/projects/minions-paradise/minion-beedo.jpg",
      "/images/projects/minions-paradise/minion-french-maid.jpg",
      "/images/projects/minions-paradise/resource-banana.jpg",
      "/images/projects/minions-paradise/resource-fireflies.jpg",
      "/images/projects/minions-paradise/resource-piranha.jpg",
      "/images/projects/minions-paradise/resource-razorclam.jpg",
      "/images/projects/minions-paradise/resource-rubbertree.jpg",
      // "/images/projects/minions-paradise/decor-camelrocks.jpg",
      // "/images/projects/minions-paradise/decor-clothesline.jpg",
      // "/images/projects/minions-paradise/decor-minionsign.jpg",
      // "/images/projects/minions-paradise/decor-toilet.jpg",
      // "/images/projects/minions-paradise/decor-totemshort.jpg",
      // "/images/projects/minions-paradise/decor-totemtall.jpg",
      // "/images/projects/minions-paradise/decor-umbrella.jpg",
      // "/images/projects/minions-paradise/leisure-hammock.jpg",
      // "/images/projects/minions-paradise/leisure-hottub.jpg",
      // "/images/projects/minions-paradise/leisure-loungechair.jpg",
      // "/images/projects/minions-paradise/leisure-throwingdisc.jpg",
      // "/images/projects/minions-paradise/unique-innertube.jpg",
      // "/images/projects/minions-paradise/unique-repairstate01.jpg",
      // "/images/projects/minions-paradise/unique-repairstate02.jpg",
      // "/images/projects/minions-paradise/unique-repairstate03.jpg",
      // "/images/projects/minions-paradise/unique-repairstate04.jpg",
      // "/images/projects/minions-paradise/unique-repairstate05.jpg",
      // "/images/projects/minions-paradise/unique-repairstate06.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 6,
    title: "Monopoly Streets",
    media: ["/images/projects/monopoly-streets/monopoly-streets-cover.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 7,
    title: "Nerf N-Strike",
    media: ["/images/projects/nerf-1/nerf-1-01.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 8,
    title: "Nerf N-Strike Elite",
    media: ["/images/projects/nerf-2/nerf-2-01.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 9,
    title: "Sims 3",
    media: [
      "/images/projects/sims-3/the-sims-3-logo.jpg",
      "/images/projects/sims-3/ep06-bear.jpg",
      "/images/projects/sims-3/ep06-chairpancake.jpg",
      "/images/projects/sims-3/ep06-gargoyal.jpg",
      "/images/projects/sims-3/ep06-photobooth02.jpg",
      "/images/projects/sims-3/ep06-seahorse.jpg",
      "/images/projects/sims-3/ep06-steampunkfurnace.jpg",
      "/images/projects/sims-3/ep07-wands.jpg",
      "/images/projects/sims-3/ep08-baristabar01.jpg",
      "/images/projects/sims-3/ep08-baristabar02.jpg",
      "/images/projects/sims-3/ep08-forgottencabin01.jpg",
      "/images/projects/sims-3/ep08-forgottencabin02.jpg",
      "/images/projects/sims-3/ep08-forgottencabin03.jpg",
      "/images/projects/sims-3/ep08-forgottencabin04.jpg",
      "/images/projects/sims-3/ep08-forgottencabin05.jpg",
      "/images/projects/sims-3/ep08-loveseatcrates.jpg",
      "/images/projects/sims-3/ep08-signbowling.jpg",
      "/images/projects/sims-3/ep08-signcoffeeshop.jpg",
      "/images/projects/sims-3/ep08-vendingmachinecandy.jpg",
      "/images/projects/sims-3/ep09-brainenhance01.jpg",
      "/images/projects/sims-3/ep09-brainenhance02.jpg",
      "/images/projects/sims-3/ep09-photobooth02.jpg",
      "/images/projects/sims-3/ep10-arch01.jpg",
      "/images/projects/sims-3/ep10-arch02.jpg",
      "/images/projects/sims-3/ep10-arch03.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 9,
    title: "Sims 4",
    media: ["/images/projects/sims-4/sims-4-cover.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 10,
    title: "Sims Freeplay",
    media: [
      "/images/projects/sims-freeplay/sims-freeplay-cover.jpg",
      "/images/projects/sims-freeplay/sims-freeplay-barnAssets-01.jpg",
      "/images/projects/sims-freeplay/sims-freeplay-barnAssets-02.jpg",
      "/images/projects/sims-freeplay/sims-freeplay-barnAssets-03.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 11,
    title: "Sims Mobile",
    media: ["/images/projects/sims-mobile/sims-mobile-cover.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 12,
    title: "Tropicana Tropolis",
    media: [
      "/images/projects/tropicana-tropolis/tropolis-cover.jpg",
      "/images/projects/tropicana-tropolis/tropolis-mockup.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b1.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b2.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b3.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b4.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b5.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b6.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b7.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b8.jpg",
      "/images/projects/tropicana-tropolis/tropolis-screens-fullsite-b9.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketch1.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketch2.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches1.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches2.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches3.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches4.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches5.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches6.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches7.jpg",
      "/images/projects/tropicana-tropolis/tropolis-sketches8.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 13,
    title: "Akrasia",
    media: [
      "/images/projects/akrasia/akrasia-01.jpg",
      "/images/projects/akrasia/akrasia-02.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 14,
    title: "O Captain",
    media: ["/images/projects/o-captain/o-captain-01.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
];
