export const projectsData = [
  // { example
  //   id: 0,
  //   title: "Paint Your Pixture",
  //   media:  [
  //     "https://www.youtube.com/embed/v_7VDm1LEqY?enablejsapi=1&rel=0",
  //     "/images/projects/paint-your-picture/paint-your-picture-01-clip.mp4",
  //     "/images/projects/paint-your-picture/paint-your-picture-cover.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-01.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-02.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-03.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-04.jpg",
  // ],
  //   links: [],
  //   description:
  //     "This was a site challenge to match the css style requirements from an image.",
  //   tags: [
  //     "React",
  //     "CSS",
  //     "Sass",
  //     "Unreal Engine",
  //     "Photoshop",
  //     "Nodejs",
  //     "UX",
  //     "Vite",
  //   ],
  //   achievements: [
  //     "Made functional site from static image within a given time frame.",
  //     "Leaned new css tricks. The corner fold.",
  //     "Side bar fades on page scroll position.",
  //     "Used gsap to make cool staggered animations and transitions.",
  //   ],
  // },
  {
    id: 1,
    title: "Star Wars Secrets of the Empire",
    media: ["/images/projects/star-wars/star-wars-01.jpg"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 2,
    title: "Ghostbusters",
    media: [
      "/images/projects/ghostbusters/ghostbusters-01.jpg",
      "/images/projects/ghostbusters/ghostbusters-02.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 3,
    title: "Athletic Apparel Customizer",
    media: [
      "https://www.youtube.com/embed/v_7VDm1LEqY?enablejsapi=1&rel=0",
      "/images/projects/fsg-builder/fsg-builder-01.jpg",
      "/images/projects/fsg-builder/fsg-builder-02.jpg",
      "/images/projects/fsg-builder/fsg-builder-03.jpg",
      "/images/projects/fsg-builder/fsg-builder-04.jpg",
      "/images/projects/fsg-builder/fsg-builder-05.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 4,
    title: "Athletic Apparel Store",
    media: [
      "/images/projects/fsg-store/fsg-store-01.jpg",
      "/images/projects/fsg-store/fsg-store-02.jpg",
      "/images/projects/fsg-store/fsg-store-03.jpg",
      "/images/projects/fsg-store/fsg-store-04.jpg",
      "/images/projects/fsg-store/fsg-store-05.jpg",
      "/images/projects/fsg-store/fsg-store-06.jpg",
      "/images/projects/fsg-store/fsg-store-07.jpg",
      "/images/projects/fsg-store/fsg-store-08.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 5,
    title: "Minions Paradise",
    media: [
      "/images/projects/minions-paradise/minions-paradise-cover.jpg",
      "/images/projects/minions-paradise/unique-cruiseship.jpg",
      "/images/projects/minions-paradise/minion-base.jpg",
      "/images/projects/minions-paradise/minion-beedo.jpg",
      "/images/projects/minions-paradise/minion-french-maid.jpg",
      "/images/projects/minions-paradise/resource-banana.jpg",
      "/images/projects/minions-paradise/resource-fireflies.jpg",
      "/images/projects/minions-paradise/resource-piranha.jpg",
      "/images/projects/minions-paradise/resource-razorclam.jpg",
      "/images/projects/minions-paradise/resource-rubbertree.jpg",
      "/images/projects/minions-paradise/decor-camelrocks.jpg",
      "/images/projects/minions-paradise/decor-clothesline.jpg",
      "/images/projects/minions-paradise/decor-minionsign.jpg",
      "/images/projects/minions-paradise/decor-toilet.jpg",
      "/images/projects/minions-paradise/decor-totemshort.jpg",
      "/images/projects/minions-paradise/decor-totemtall.jpg",
      "/images/projects/minions-paradise/decor-umbrella.jpg",
      "/images/projects/minions-paradise/leisure-hammock.jpg",
      "/images/projects/minions-paradise/leisure-hottub.jpg",
      "/images/projects/minions-paradise/leisure-loungechair.jpg",
      "/images/projects/minions-paradise/leisure-throwingdisc.jpg",
      "/images/projects/minions-paradise/unique-innertube.jpg",
      "/images/projects/minions-paradise/unique-repairstate01.jpg",
      "/images/projects/minions-paradise/unique-repairstate02.jpg",
      "/images/projects/minions-paradise/unique-repairstate03.jpg",
      "/images/projects/minions-paradise/unique-repairstate04.jpg",
      "/images/projects/minions-paradise/unique-repairstate05.jpg",
      "/images/projects/minions-paradise/unique-repairstate06.jpg",
    ],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
];
