export const projectsData = [
  // { example
  //   id: 0,
  //   date: "2066 - 2077",
  //   title: "Paint Your Pixture",
  //   media:  [
  //     "https://www.youtube.com/embed/v_7VDm1LEqY?enablejsapi=1&rel=0",
  //     "/images/projects/paint-your-picture/paint-your-picture-01-clip.mp4",
  //     "/images/projects/paint-your-picture/paint-your-picture-cover.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-01.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-02.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-03.jpg",
  //     "/images/projects/paint-your-picture/paint-your-picture-04.jpg",
  // ],
  //   links: [],
  //   description:
  //     "This was a site challenge to match the css style requirements from an image.",
  //   tags: [
  //     "React",
  //     "CSS",
  //     "Sass",
  //     "Unreal Engine",
  //     "Photoshop",
  //     "Nodejs",
  //     "UX",
  //     "Vite",
  //   ],
  //   achievements: [
  //     "Made functional site from static image within a given time frame.",
  //     "Leaned new css tricks. The corner fold.",
  //     "Side bar fades on page scroll position.",
  //     "Used gsap to make cool staggered animations and transitions.",
  //   ],
  // },
  {
    id: 1,
    date: "Jun 2021 - Present",
    title: "Adobe",
    media: ["/images/companies/adobe-logo.png"],
    links: [
      { type: "Youtube", url: "https://www.youtube.com/watch?v=8Fc5HB8nT8Y" },
      {
        type: "Documentation",
        url:
          "https://experienceleague.adobe.com/en/docs/workfront/using/review-and-approve-work/document-reviews-and-approvals/wf-ai-reviewer",
      },
    ],
    description:
      "I architected and built an AI image detection tool to improve accuracy and speed approval processes.",

    tags: ["Top 5", ,],
    achievements: [
      "I take pride on being the inventor for this product",
      "From garage week project to full release",
      "Adobe Summit headliner 2 years in a row",
      "Granted a small task force to deliver final product",
    ],
  },
  {
    id: 2,
    date: "Jul 2020 - Jun 2021",
    title: "Basecamp Franchising",
    media: ["/images/companies/basecamp-franchising-logo.png"],
    links: [],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["React", "CSS", "Nodejs", "Top 5"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 3,
    date: "Jun 2018 - Jul 2020",
    title: "Founder Sport Group",
    media: ["/images/companies/founder-sport-group-logo.png"],
    links: [
      { type: "github", url: "https://github.com" },
      { type: "site", url: "https://example.com" },
    ],
    description:
      "This was a site challenge to match the css style requirements from an image.",
    tags: ["Top 5"],
    achievements: [
      "Made functional site from static image within a given time frame.",
      "Leaned new css tricks. The corner fold.",
      "Side bar fades on page scroll position.",
      "Used gsap to make cool staggered animations and transitions.",
    ],
  },
  {
    id: 4,
    date: "Jan 2018 - Apr 2018",
    title: "Dev Mountain",
    media: ["/images/companies/dev-mountain-logo.png"],
    links: [],
    description: "A virtual reality experience made for Disney!",
    tags: ["Education"],
    achievements: [
      "Built edge normalizer tool to achieve smooth bevels with minimal geometry.",
      "Created Story board and animatic for whole experience.",
      "Featured at DisneyLand and Disney World resorts is quite a badge of honor.",
      "Getting to work with Disney and Star Wars!",
    ],
  },
  {
    id: 5,
    date: "Feb 2016 - Oct 2017",
    title: "The Void",
    media: ["/images/companies/void-logo.png"],
    links: [],
    description: "A Virtual Reality experience made at the Void.",
    tags: ["Video Games", "Virtual Reality"],
    achievements: [
      "Small team great results! Proud to be on a small team and achieve something this big.",
      "Learned limitations and how to work within restraints of Virtual Reality.",
      "Built a skin-weight transferring tool, and mass obj exporter increasing productivity by 20%",
      "Art skills used: Story Boarding, Concept Art, 3d Modeling and Animation.",
    ],
  },
  {
    id: 6,
    date: "Mar 2011 - Feb 2016",
    title: "Electronic Arts",
    media: ["/images/companies/electronic-arts-logo.png"],
    links: [],
    description: "An athletic apparel customization tool.",
    tags: ["Top 5"],
    achievements: [
      "I was in charge of visual representation of the data on canvas and canvas interactions.",
      "Used Pythagorean theorem and other math formulas to match scale, detect edges and resize elements.",
      "Organize a giant yet powerful redux state to manage iteraction accross app and canvas.",
    ],
  },
  {
    id: 7,
    date: "Dec 2010 - Jan 2011",
    title: "Riser Media",
    media: ["/images/companies/riser-media-logo.png"],
    links: [],
    description:
      "A ecomerce store used to catalogued, displayed and purchase athletic apparel.",
    tags: ["Top 5"],
    achievements: [
      "Made universal image component used on all pages. Leveraging reacts component based architecture.",
      "Created the multi-tier filtering system to sort through over 2000 products.",
      "Set up a component based svg system to allow javascript to control svg's dynamically.",
      "Even though I was a Software Engineer, I also got tasked with the UX Design and Mockups.",
    ],
  },
  {
    id: 8,
    date: "2004 - 2007",
    title: "Art Institute",
    media: ["/images/companies/art-institute-logo.png"],
    links: [],
    description:
      "A ecomerce store used to catalogued, displayed and purchase athletic apparel.",
    tags: ["Education", "Top 5"],
    achievements: [
      "Made universal image component used on all pages. Leveraging reacts component based architecture.",
      "Created the multi-tier filtering system to sort through over 2000 products.",
      "Set up a component based svg system to allow javascript to control svg's dynamically.",
      "Even though I was a Software Engineer, I also got tasked with the UX Design and Mockups.",
    ],
  },
];
